apiVersion: v1
kind: Secret
metadata:
  name: yas-postgresql-credentials-secret
  namespace: yas-dev
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tax
  namespace: yas-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tax
  template:
    metadata:
      labels:
        app: postgres-tax
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: tax
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-tax
  namespace: yas-dev
spec:
  selector:
    app: postgres-tax
  ports:
    - port: 5432
      targetPort: 5432
